# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
#
# Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
# Pentagonal	Pn=n(3n−1)/2	1, 5, 12, 22, 35, ...
# Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.
#
# Find the next triangle number that is also pentagonal and hexagonal.

i = 0
tri = 0
pen = 0
hex = 0
target = 100000

triangular = []
pentagonal = []
hexagonal = []

while i < target:
    tri = int(i * (i + 1) / 2)
    pen = int(i * ((3 * i - 1) / 2))
    hex = int(i * (2 * i - 1))
    triangular.append(tri)
    pentagonal.append(pen)
    hexagonal.append(hex)
    i = i + 1

triangular.remove(0)
pentagonal.remove(0)
hexagonal.remove(0)

i = 0

while i < triangular.__len__():
    if pentagonal.__contains__(triangular[i]):
        if hexagonal.__contains__(triangular[i]):
            print(triangular[i],"---------------------------------------")
    i = i + 1
    # print("i",i)

print(triangular[i], "---------------------------------------")
